### PR TITLE
Feature/w50 228/style publications page

### PR DESCRIPTION
**Pull request by gevuong**
Summary of code changes:

- Overhauled existing styling and component implementation to improve readability and maintainability.
- Styled component for desktop, tablet, and mobile view.
- Change route casing from PascalCase to kebab-case to follow better practice for url naming conventions.
- Updated metadata in English and Spanish along with its type definitions to reflect the new content layout.

**Note**: The codebase for the www.virufy.org/study/welcome webpage does not appear to be in this repo. Before working on the modal, If possible, I would like to first reference that codebase for context, rather than building the modal component from scratch. I will defer the modal to a separate ticket.

Desktop view:
Screenshot 2024-04-29 at 6 55 40 PM

Tablet view:
Screenshot 2024-04-29 at 6 56 03 PM

Mobile view:
Screenshot 2024-04-29 at 6 56 28 PM
Screenshot 2024-04-29 at 6 56 41 PM

### CODE REVIEW

**Review by a-wong-8 — APPROVED** [review]
it looks beautiful 👍🏼

**Comment by junghoona** [comment]
Looks great! Awesome work @gevuong

**Review by junghoona — APPROVED** [review]
Looks great! Awesome work @gevuong

**Comment by gevuong** [comment]
Thanks for taking the time to review! Will be merging shortly..

**Pull request merged**
