### PR TITLE
[W50-234]: Header and Footer

### PR DESCRIPTION
**Pull request by junghoona**
- Navbar desktop view complete

Screenshot 2024-05-07 at 10 52 33 PM

Screenshot 2024-05-07 at 10 53 03 PM

Screenshot 2024-05-07 at 10 53 55 PM

Screenshot 2024-05-07 at 10 53 24 PM

### CODE REVIEW

**Review by a-wong-8 — APPROVED** [review]
excellent work!

**Comment by gevuong** [comment]
When the language changes to Spanish, it looks like the underline disappears?

Screenshot 2024-05-07 at 4 34 12 PM

**Comment by gevuong** [comment]
According to Figma design, it looks like dropdown should have something like white text, `text-center`, and transparent or no background color?

Screenshot 2024-05-07 at 4 51 53 PM

**Comment by junghoona** [comment]
Thanks for the feedback @gevuong . I've added those styling changes

**Review by gevuong — APPROVED** [review]
Looks good! Merge when ready.

**Review by a-wong-8 — COMMENTED** [review]
a few things I found doing the qa. i think you can merge it and fix them later: 

1. footer active link underline not correct for active page 
2. dropdown transparent bg & text in mobile view blends w page text 
3. dontate button select element missing label
4. footer doesnt change to spainish
5. missing one young world & coughchk dropdown

**Comment by junghoona** [comment]
> a few things I found doing the qa. i think you can merge it and fix them later:
> 
> 1. footer active link underline not correct for active page
> 2. dropdown transparent bg & text in mobile view blends w page text
> 3. dontate button select element missing label
> 4. footer doesnt change to spainish
> 5. missing one young world & coughchk dropdown

Gotcha @a-wong-8, I'll take note of that. Merging it for now.

**Pull request merged**
