### PR TITLE
[W50-227]: Build 'Amil's Story' page - Website 6.0

### PR DESCRIPTION
**Pull request by junghoona**
- Added Youtube Video Thumbnail:
Screenshot 2024-04-19 at 5 45 34 PM

- Added Gradient Background
- Replaced Images:
Screenshot 2024-04-19 at 5 45 47 PM

Screenshot 2024-04-19 at 5 46 00 PM

Screenshot 2024-04-19 at 5 46 13 PM

- Added rounded background for Amil's Publications:
Screenshot 2024-04-19 at 5 46 21 PM

- Formatted Text

### CODE REVIEW

**Comment by gevuong** [comment]
Are the 9k+ line changes related to the ticket? My suggestion would be to defer formatting to either W50-195 or W50-196, or to the individual tickets that are related to those pages and images. However, the formatting for the files that are related to this ticket can remain. Thoughts?

**Comment by amilkh** [comment]
Thank you so much guys! I would go ahead and push it and send me the live page by email. I can review it and we can make more changes

**Review by a-wong-8 — COMMENTED** [review]
i'm curious, why are there so many changes?

**Review by a-wong-8 — COMMENTED** [review]
oh yeah, you need to merge into release branch and not develp branch

**Comment by a-wong-8** [comment]
also it looks like the spacing is off between the imgs and text; in the figma, it looks more uniform and in a grid. Other than that, it looks good!

**Comment by gevuong** [comment]
Closing PR due to unrelated code changes stemming from branching off of `develop` and not `release`, and/or comparing code changes to the `develop` branch.

**Pull request closed without merging**
