### PR TITLE
Feature/w50 221/style about us page

### PR DESCRIPTION
**Pull request by gevuong**
Summary of code changes:

- Overhauled existing styling and component implementation to improve readability and maintainability.
- Styled component for desktop and mobile view.
- Change route casing from PascalCase to kebab-case to follow better practice for url naming conventions.
- Updated metadata in English and Spanish along with its type definitions to reflect the new content layout.
- Added 2 missing images that were causing build errors.

Desktop View:
Screenshot 2024-04-25 at 5 23 01 PM
Screenshot 2024-04-25 at 5 23 19 PM

Mobile/Tablet View:
Screenshot 2024-04-25 at 5 25 14 PM
Screenshot 2024-04-25 at 5 26 18 PM

### CODE REVIEW

**Review by a-wong-8 — COMMENTED** [review]
your page looks fire !

**Comment by gevuong** [comment]
Summary of code changes:
1. Overhauled existing styling and component implementation to improve readability and maintainability.
2. Styled component for desktop and mobile view.
2. Change route casing from PascalCase to kebab-case to follow better practice for url naming conventions.
3. Updated metadata in English and Spanish along with its type definitions to reflect the structure and outline of the new content layout.
4. Added 2 missing images that were causing build errors.

**Review by a-wong-8 — COMMENTED** [review]
looks good. are going to add the absolute to the drop down ?

**Comment by gevuong** [comment]
Sure, I'll add that

**Pull request merged**
