### PR TITLE
Read for review: Join our team- Job Description Page

### PR DESCRIPTION
**Pull request by ridham-virufy**
Built the Job Description Page according to the Figma design for the new website 6.0. 

[Desktop view FIgma](https://www.figma.com/design/CJVubKy4QZETjVty3Ak4eK/Website-6.0?node-id=2734-9048&t=PUr3Kg7RqMQYPZdv-1)
[Mobile view Figma](https://www.figma.com/design/CJVubKy4QZETjVty3Ak4eK/Website-6.0?node-id=2756-10222&t=tuMr8Tu6Rrp92Y2s-1)

Screenshots from the localhost:
Screenshot 2024-06-24 at 9 36 20 AM
Screenshot 2024-06-24 at 9 36 28 AM
Screenshot 2024-06-24 at 9 36 37 AM
Screenshot 2024-06-24 at 9 37 07 AM
Screenshot 2024-06-24 at 9 37 16 AM
Screenshot 2024-06-24 at 9 37 22 AM

The job listings page and the pop-up for volunteers to agree that all positions are unpaid will be worked on by Anthony. 
Let me know if there are any suggestions for my part of the website.

[https://deploy-preview-34--creative-jalebi-f8e18b.netlify.app/JobListing/1](https://deploy-preview-34--creative-jalebi-f8e18b.netlify.app/JobListing/1) is the link for individual Job Descriptions. the base json file will have to be updated by Frederick or Gabriela for more positions. Currently there are only 2 in them.

### CODE REVIEW

**Review by a-wong-8 — COMMENTED** [review]
@ridham-virufy the text is off center at 1024 px 
Screenshot 2024-06-24 at 2 10 55 PM

**Comment by ridham-virufy** [comment]
> @ridham-virufy the text is off center at 1024 px Screenshot 2024-06-24 at 2 10 55 PM

Can you check it now?

**Comment by gevuong** [comment]
Requested changes are referenced in this comment https://github.com/virufy6/virufy6.github.io/pull/30#issuecomment-2192180011. Lmk if you have any questions.

**Comment by ridham-virufy** [comment]
> Requested changes are referenced in this comment [#30 (comment)](https://github.com/virufy6/virufy6.github.io/pull/30#issuecomment-2192180011). Lmk if you have any questions.

@gevuong @a-wong-8 I am deleting this pull request, please refer #37 for the same. It has all the extra commits reverted.

**Pull request closed without merging**
