### PR TITLE
Feature/w50 243/build faq page

### PR DESCRIPTION
**Pull request by gevuong**
Summary

https://deploy-preview-35--creative-jalebi-f8e18b.netlify.app/faq

**Functionality**
1. Add search functionality with debounce set to 500ms to reduce number of re-renders.
2. User can filter questions using input text search.
3. User can filter questions by selecting an FAQ Topic.
4. User can filter questions using input text search + selecting an FAQ Topic.
5. User can only select 1 FAQ Topic at a time.
6. User can select and deselect an FAQ Topic. Deselecting a topic will render all 'Common Questions'.
7. Use kebab-casing for `/faq` route.
8. Redesigned metadata types and structures to reflect layout of page.
9. Add `lodash.debounce` library.
10. Memoized `allQuestions` and `handleSearchInputChange` since these values do not change on re-render. This will reduce the computation cost on every re-render.

**Style and Formatting**
1. Styled page to be responsive from 320px (Mobile S) to 2560px (4k).
2. Add 500ms transitions to accordion dropdown and arrow icon.
3. Organized imports.
4. Replace metadata files suffixed with `.tsx` to `.ts`.

Screenshot 2024-06-26 at 1 21 41 PM

Screenshot 2024-06-26 at 1 22 09 PM

### CODE REVIEW

**Review by a-wong-8 — COMMENTED** [review]
why yo build failed??!

**Comment by gevuong** [comment]
I'll check later tn. Local build passes tho..

**Comment by ridham-virufy** [comment]
Great work, no suggestions

**Review by a-wong-8 — APPROVED** [review]
this page is fire 🔥

**Comment by nayshajain** [comment]
@gevuong The page looks great! 🙌 Just need to add more FAQ content according to https://docs.google.com/spreadsheets/d/1oUkbhoo6ocLJbgP1qw_GpVP-x4kJ9FG0YzTCKpRvuP0/edit?gid=0#gid=0.

**Pull request merged**
