### PR TITLE
[W50-227]: Amil's Story page

### PR DESCRIPTION
**Pull request by junghoona**
Desktop View (Mobile View Needs Work): 

Screenshot 2024-04-26 at 11 51 12 AM
Screenshot 2024-04-26 at 11 51 49 AM
Screenshot 2024-04-26 at 11 52 05 AM
Screenshot 2024-04-26 at 11 52 17 AM
Screenshot 2024-04-26 at 11 52 28 AM

### CODE REVIEW

**Review by a-wong-8 — COMMENTED** [review]
good work, but can you change the alignment of the images and text so that it matches the figma? 
Screenshot 2024-04-26 at 10 07 45 AM
Screenshot 2024-04-26 at 10 07 32 AM

**Comment by gevuong** [comment]
Hey @junghoona, thank you for re-creating the PR with only the changes pertaining to Amil's story page! It's much easier to follow and review the PR. I'm not expecting page updates to be pixel perfect, but I would like them to be somewhat responsive, even in desktop view, which I assume includes laptop views.

Have you looked at the page when the screen size is at a laptop view of 1024px? I'm noticing the text pulls the images downward, which I think can result in poor user experience. Here are some screenshots of this occurring.

Please let us know if you need help.

Screenshot 2024-04-26 at 1 26 29 PM

Screenshot 2024-04-26 at 1 26 41 PM

**Comment by junghoona** [comment]
Thanks for the feedbacks @gevuong and @a-wong-8. I was taking a look at Website 4.0 for reference, but it seems mobile view was never implemented for 4.0, at least for Amil's story page. Any advice/suggestions on how I could start without affecting the desktop view?

**Comment by junghoona** [comment]
@a-wong-8, Desktop view should match closer to Figma. Feel free to let me know what you think about the changes

**Comment by a-wong-8** [comment]
it's better but still not perfect... have you tired using display grid? what do you think @gevuong ?

**Review by gevuong — COMMENTED** [review]
Looks good enough. It can be revised when working on the mobile view. Thanks @junghoona!

One more thing, can you revert step1 and step2 images to its original size?
For more details: https://github.com/virufy6/virufy6.github.io/pull/8#pullrequestreview-2029504388

**Comment by a-wong-8** [comment]
it looks better but the whole page looks off center on desktop view. Also the last img looks skewed as deepika mentioned. excellent progress though! 
Screenshot 2024-05-02 at 6 38 02 PM

**Review by a-wong-8 — COMMENTED** [review]
hey john, the page is still off center. I was able to fix it in devtools by setting margin-left and margin-right to auto or .mx-auto , try it out

**Comment by junghoona** [comment]
> hey john, the page is still off center. I was able to fix it in devtools by setting margin-left and margin-right to auto or .mx-auto , try it out

Thanks for the suggestion @a-wong-8! Page layout should be centered and consistent for `375px`, `425px`, `768px`, `1024px`, `1440px` and `2560px` screen view. 

To point out, I've noticed that adding `mx-auto` does distort the page layout as the page increases or decreases in size for unspecified page dimensions. For this, I could use help for code velocity, as this PR has been pending for over 2 weeks now.

**Comment by gevuong** [comment]
I can take a look at it tm or Tuesday to see what's going on with the page distortion and stretched image.

**Comment by junghoona** [comment]
> I can take a look at it tm or Tuesday to see what's going on with the page distortion and stretched image.

I think it's ready for merge. Feel free to review and refactor more.

**Review by gevuong — APPROVED** [review]
Looks good, awesome work! Feel free to merge when you're ready.

**Review by a-wong-8 — APPROVED** [review]
excellent work!

**Pull request merged**
