### PR TITLE
[W50-234]: Header and Footer

### PR DESCRIPTION
**Pull request by junghoona**
Updated Footer for desktop view (Mobile View needs work):
Screenshot 2024-04-26 at 9 03 29 PM

TODO: 
- Update Header (navbar)
- Update Footer for mobile view

### CODE REVIEW

**Review by a-wong-8 — COMMENTED** [review]
excellent work, it looks good so far! but the underline of the link should stay active on the current page/link

**Review by alinalari — APPROVED** [review]
Looks good!

**Comment by gevuong** [comment]
@junghoona so I understand the scope of this PR, it addresses only the footer desktop view and not the header correct?

**Comment by junghoona** [comment]
Correct @gevuong. Still working on the Header/Navbar so the ticket is IP. 
Since Alina approved the PR and it doesn't break anything in production, can I merge the current changes into `release`?

I'll continue working on [W50-234] on this branch and can submit another PR after the mobile view and header is done.

**Comment by gevuong** [comment]
@junghoona were you ever able to look into @a-wong-8 comment's on how to implement "the underline of the link should stay active on the current page/link"? I usually wouldn't consider it a big deal but it looks like the underline exists on every page design in Figma. If you did look into it and couldn't figure it out, let us know and one of us can possibly take a look at it.

Also, reminder to resolve conflicts before merge. If you need help with any of this, please let us know.

**Comment by junghoona** [comment]
Thanks for the feedback @a-wong-8.
Hey @gevuong, no problem. I'll resolve those conflicts before merging this current PR, thanks for the input.

**Review by gevuong — COMMENTED** [review]
Nice, thanks for making the requested changes! One more thing, can you revert the step1 and step2 images to its original size? Those images are already in the release branch and can be found here:

https://github.com/virufy6/virufy6.github.io/blob/release/src/assets/static/images/howItWorks/step1.jpg
https://github.com/virufy6/virufy6.github.io/blob/release/src/assets/static/images/howItWorks/step2.jpg

**Comment by junghoona** [comment]
> Nice, thanks for making the requested changes! One more thing, can you revert the step1 and step2 images to its original size? Those images are already in the release branch and can be found here:
> 
> https://github.com/virufy6/virufy6.github.io/blob/release/src/assets/static/images/howItWorks/step1.jpg https://github.com/virufy6/virufy6.github.io/blob/release/src/assets/static/images/howItWorks/step2.jpg

No problem! I updated the images. I'm going to merge these changes for the footer into `release` now

**Pull request merged**
