### PR TITLE
Content update naysha

### PR DESCRIPTION
**Pull request by nayshajain**
Updates on the Supporters page, OYW, FAQ, Join Team, and Disease Information pages. 
Requested changes are documented in: https://docs.google.com/document/d/1isZiE1mJKFrgvvVvrW5qFeaQ5LkImQ2QB671ezzeFrs/edit?pli=1

Disease Information Pages were created earlier.
The OYW team leads have been mixed and Shreya was added earlier.

--> Home Page
Instead of "Your Personal Health Companion", it now reads as "Your Digital Health Companion".
Home Page

--> Supporters
Removed the Stanford Medicine Logo
removed standford logo

--> One Young World
OYW

--> Join Team Page
Join our team

### CODE REVIEW

**Comment by ridham-virufy** [comment]
@gevuong Will, it be better if we assign the same ticket to Naysha for the new minimal repo? if so then She can get started with the same updates there.

**Review by ridham-virufy — APPROVED** [review]
Great Work!

**Comment by gevuong** [comment]
Invite sent to @nayshajain

**Review by a-wong-8 — APPROVED** [review]
excellent work

**Comment by nayshajain** [comment]
@ridham-virufy @gevuong sounds good!

**Pull request merged**
